// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClVjGuds4bjyFulohZCpOJXSo79JHQhoE',
    appId: '1:1090102585003:web:2b936917f16b6e9ddab9ee',
    messagingSenderId: '1090102585003',
    projectId: 'dcliclogement',
    authDomain: 'dcliclogement.firebaseapp.com',
    storageBucket: 'dcliclogement.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdT-w_yn-QD4Htjf8kYxVVXf3IAqArvT0',
    appId: '1:1090102585003:android:389bd0f0dc00d990dab9ee',
    messagingSenderId: '1090102585003',
    projectId: 'dcliclogement',
    storageBucket: 'dcliclogement.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBF4E56RHSFP4kHCDPyVvcvDqKde1dt1RA',
    appId: '1:1090102585003:ios:8d97957d315485b9dab9ee',
    messagingSenderId: '1090102585003',
    projectId: 'dcliclogement',
    storageBucket: 'dcliclogement.firebasestorage.app',
    iosClientId: '1090102585003-6ett5kee1c3tu5cijntt4h1nk14k13qn.apps.googleusercontent.com',
    iosBundleId: 'com.example.houeffaLog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBF4E56RHSFP4kHCDPyVvcvDqKde1dt1RA',
    appId: '1:1090102585003:ios:8d97957d315485b9dab9ee',
    messagingSenderId: '1090102585003',
    projectId: 'dcliclogement',
    storageBucket: 'dcliclogement.firebasestorage.app',
    iosClientId: '1090102585003-6ett5kee1c3tu5cijntt4h1nk14k13qn.apps.googleusercontent.com',
    iosBundleId: 'com.example.houeffaLog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClVjGuds4bjyFulohZCpOJXSo79JHQhoE',
    appId: '1:1090102585003:web:d216081597d61d3ddab9ee',
    messagingSenderId: '1090102585003',
    projectId: 'dcliclogement',
    authDomain: 'dcliclogement.firebaseapp.com',
    storageBucket: 'dcliclogement.firebasestorage.app',
  );
}
